// frontend/utils/biomarkers.ts

export interface BiomarkerExplanation {
  simpleName: string;
  category: string;
  description: string;
  whatItMeans: string;
  criticalIf: string;
}

export const BIOMARKER_EXPLANATIONS: Record<string, BiomarkerExplanation> = {
  // Blood sugar
  "glucose": {
    simpleName: "Blood Sugar (Glucose)",
    category: "Metabolism",
    description: "The main source of energy for your body's cells, carried through the bloodstream.",
    whatItMeans: "Indicates how well your body processes sugars. High levels can indicate diabetes or pre-diabetes.",
    criticalIf: "Extremely high (>126 mg/dL fasting) or low (<70 mg/dL), which requires immediate attention."
  },
  "hba1c": {
    simpleName: "Average Blood Sugar (HbA1c)",
    category: "Metabolism",
    description: "Measures your average blood sugar levels over the past 3 months.",
    whatItMeans: "Used to diagnose and monitor diabetes. Higher levels mean poorer blood sugar control.",
    criticalIf: "Levels above 6.5% indicate diabetes; above 8% requires immediate medical consultation."
  },
  // Liver
  "sgpt": {
    simpleName: "SGPT (ALT) - Liver Enzyme",
    category: "Liver Health",
    description: "An enzyme found mostly in liver cells. When the liver is damaged, it leaks SGPT into the blood.",
    whatItMeans: "Used to evaluate liver function. High levels suggest liver injury or inflammation.",
    criticalIf: "Elevations above 3 times the upper limit (>150 U/L) indicate acute liver inflammation."
  },
  "alt": {
    simpleName: "SGPT (ALT) - Liver Enzyme",
    category: "Liver Health",
    description: "An enzyme found mostly in liver cells. When the liver is damaged, it leaks ALT/SGPT into the blood.",
    whatItMeans: "Used to evaluate liver function. High levels suggest liver injury or inflammation.",
    criticalIf: "Elevations above 3 times the upper limit (>150 U/L) indicate acute liver inflammation."
  },
  "sgot": {
    simpleName: "SGOT (AST) - Liver/Muscle Enzyme",
    category: "Liver Health",
    description: "An enzyme found in the liver, heart, and muscles.",
    whatItMeans: "High levels suggest liver, muscle, or heart stress/damage.",
    criticalIf: "Elevations above 3 times the upper limit (>120 U/L) require diagnostic workup."
  },
  "ast": {
    simpleName: "SGOT (AST) - Liver/Muscle Enzyme",
    category: "Liver Health",
    description: "An enzyme found in the liver, heart, and muscles.",
    whatItMeans: "High levels suggest liver, muscle, or heart stress/damage.",
    criticalIf: "Elevations above 3 times the upper limit (>120 U/L) require diagnostic workup."
  },
  "bilirubin": {
    simpleName: "Bilirubin (Jaundice indicator)",
    category: "Liver Health",
    description: "A yellowish substance formed during the normal breakdown of red blood cells.",
    whatItMeans: "High levels can cause jaundice (yellow skin/eyes) and indicate liver or gallbladder issues.",
    criticalIf: "Levels above 2.0 mg/dL indicate active liver dysfunction or biliary block."
  },
  // Kidney
  "creatinine": {
    simpleName: "Creatinine (Kidney Waste)",
    category: "Kidney Health",
    description: "A chemical waste product generated by muscle metabolism, filtered out by kidneys.",
    whatItMeans: "Indicates how well your kidneys are filtering waste. High levels indicate declining kidney function.",
    criticalIf: "Levels above 1.5 mg/dL indicate kidney impairment; above 2.0 mg/dL requires urgent medical care."
  },
  "urea": {
    simpleName: "Blood Urea Nitrogen (BUN)",
    category: "Kidney Health",
    description: "A waste product formed in the liver when protein is broken down, filtered by kidneys.",
    whatItMeans: "High levels can mean kidneys aren't filtering well, or indicate dehydration/excessive protein intake.",
    criticalIf: "Levels above 40 mg/dL suggest significant dehydration or kidney damage."
  },
  // Lipids / Cholesterol
  "cholesterol": {
    simpleName: "Total Cholesterol",
    category: "Heart & Lipids",
    description: "The total amount of cholesterol (fats) in your blood.",
    whatItMeans: "Used to evaluate heart disease risk. Consists of HDL, LDL, and triglycerides.",
    criticalIf: "Levels above 240 mg/dL increase cardiovascular risk significantly."
  },
  "ldl": {
    simpleName: "LDL ('Bad' Cholesterol)",
    category: "Heart & Lipids",
    description: "Low-Density Lipoprotein, which can build up in the walls of your arteries.",
    whatItMeans: "High levels raise heart attack and stroke risks by narrowing arteries.",
    criticalIf: "Levels above 160 mg/dL (or >100 mg/dL for high-risk patients) are considered borderline/critical."
  },
  "hdl": {
    simpleName: "HDL ('Good' Cholesterol)",
    category: "Heart & Lipids",
    description: "High-Density Lipoprotein, which helps clear other forms of cholesterol from your bloodstream.",
    whatItMeans: "Higher levels are protective. Low levels increase heart disease risk.",
    criticalIf: "Levels below 40 mg/dL for men or 50 mg/dL for women increase cardiovascular risk."
  },
  "triglycerides": {
    simpleName: "Triglycerides (Blood Fats)",
    category: "Heart & Lipids",
    description: "A type of fat found in your blood, stored in fat cells for energy.",
    whatItMeans: "High levels can harden arteries or cause pancreatitis.",
    criticalIf: "Levels above 200 mg/dL are high; above 500 mg/dL is extremely critical."
  },
  // Thyroid
  "tsh": {
    simpleName: "TSH (Thyroid Stimulating Hormone)",
    category: "Thyroid Health",
    description: "A hormone that tells your thyroid gland to produce and release thyroid hormones.",
    whatItMeans: "High TSH means underactive thyroid (hypothyroidism); low TSH means overactive thyroid (hyperthyroidism).",
    criticalIf: "TSH levels below 0.1 uIU/mL or above 10.0 uIU/mL indicate significant thyroid imbalances."
  },
  // CBC
  "hemoglobin": {
    simpleName: "Hemoglobin (Oxygen Carrier)",
    category: "Blood & Iron",
    description: "The protein in red blood cells that carries oxygen from your lungs to the rest of your body.",
    whatItMeans: "Low levels indicate anemia, leading to fatigue and weakness. High levels can suggest dehydration.",
    criticalIf: "Levels below 10 g/dL indicate moderate-to-severe anemia; below 7 g/dL is life-threatening."
  },
  "wbc": {
    simpleName: "White Blood Cells (Immune Cells)",
    category: "Immunity",
    description: "Cells that help the body fight infections and diseases.",
    whatItMeans: "High levels indicate infection or inflammation; low levels suggest weak immunity.",
    criticalIf: "Levels below 3,000 /uL or above 15,000 /uL require immediate diagnostic workup."
  },
  "platelets": {
    simpleName: "Platelets (Clotting Cells)",
    category: "Blood & Iron",
    description: "Small cell fragments that help your blood clot to stop bleeding.",
    whatItMeans: "Low platelets cause easy bruising/bleeding; high platelets can cause unwanted blood clots.",
    criticalIf: "Levels below 100,000 /uL (risk of bleeding) or above 450,000 /uL (risk of clotting)."
  }
};

export function getBiomarkerExplanation(name: string): BiomarkerExplanation {
  const normKey = name.toLowerCase().replace(/[\s\-_]/g, "");
  for (const [key, value] of Object.entries(BIOMARKER_EXPLANATIONS)) {
    if (normKey.includes(key) || key.includes(normKey)) {
      return value;
    }
  }
  return {
    simpleName: name,
    category: "General Health",
    description: `A vital health biomarker extracted from your laboratory reports.`,
    whatItMeans: "Monitors general health and metabolic functions.",
    criticalIf: "Refer to the lab report reference ranges for exact low/high limits."
  };
}
