"""add active_profile_id to users

Revision ID: 49ebb3aaf75a
Revises: 4158b4762bd1
Create Date: 2026-06-11 19:01:06.692808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49ebb3aaf75a'
down_revision: Union[str, Sequence[str], None] = '4158b4762bd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_insights', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('ai_insights', sa.Column('risk_level', sa.String(length=50), nullable=True))
    op.add_column('ai_insights', sa.Column('recommendations', sa.Text(), nullable=True))
    op.add_column('ai_insights', sa.Column('confidence_score', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('ai_insights', sa.Column('provider', sa.String(length=50), nullable=True))
    op.add_column('ai_insights', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('ai_insights', 'report_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('ai_insights', 'insight_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('ai_insights', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('ai_insights', 'severity',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('ai_insights', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_ai_insights_insight_type'), 'ai_insights', ['insight_type'], unique=False)
    op.create_index(op.f('ix_ai_insights_report_id'), 'ai_insights', ['report_id'], unique=False)
    op.create_index(op.f('ix_ai_insights_risk_level'), 'ai_insights', ['risk_level'], unique=False)
    op.create_index(op.f('ix_ai_insights_severity'), 'ai_insights', ['severity'], unique=False)
    op.add_column('biomarkers', sa.Column('severity', sa.String(), nullable=True))
    op.add_column('biomarkers', sa.Column('reference_range', sa.String(), nullable=True))
    op.add_column('biomarkers', sa.Column('clinical_significance', sa.Text(), nullable=True))
    op.add_column('biomarkers', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('biomarkers', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('biomarkers', 'report_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('biomarkers', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('biomarkers', 'value',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('biomarkers', 'unit',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('biomarkers', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('biomarkers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('biomarkers_report_id_fkey'), 'biomarkers', type_='foreignkey')
    op.create_foreign_key(None, 'biomarkers', 'reports', ['report_id'], ['id'])
    op.drop_column('biomarkers', 'is_abnormal')
    op.add_column('profiles', sa.Column('firebase_uid', sa.String(length=255), nullable=False))
    op.alter_column('profiles', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('profiles', 'gender',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('profiles', 'blood_group',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('profiles', 'relationship_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text("'Self'::text"))
    op.alter_column('profiles', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_profiles_firebase_uid'), 'profiles', ['firebase_uid'], unique=False)
    op.drop_constraint(op.f('profiles_user_id_fkey'), 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'])
    op.add_column('reference_biomarkers', sa.Column('severity_weight', sa.Float(), nullable=True))
    op.alter_column('reference_biomarkers', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('reference_biomarkers', 'aliases',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('reference_biomarkers', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('reference_biomarkers', 'unit',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('reference_biomarkers', 'gender',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('reference_biomarkers', 'age_group',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('reference_biomarkers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reference_biomarkers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_reference_biomarkers_aliases'), 'reference_biomarkers', ['aliases'], unique=False)
    op.create_index(op.f('ix_reference_biomarkers_name'), 'reference_biomarkers', ['name'], unique=False)
    op.add_column('reports', sa.Column('firebase_uid', sa.String(length=255), nullable=False))
    op.alter_column('reports', 'profile_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('reports', 'scan_job_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('reports', 'report_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text("'LAB_REPORT'::text"))
    op.alter_column('reports', 'original_filename',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('reports', 'stored_filename',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('reports', 'mime_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('reports', 'hospital_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_reports_firebase_uid'), 'reports', ['firebase_uid'], unique=False)
    op.drop_constraint(op.f('reports_scan_job_id_fkey'), 'reports', type_='foreignkey')
    op.drop_constraint(op.f('reports_profile_id_fkey'), 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'scan_jobs', ['scan_job_id'], ['id'])
    op.create_foreign_key(None, 'reports', 'profiles', ['profile_id'], ['id'])
    op.add_column('scan_jobs', sa.Column('stored_filename', sa.String(), nullable=False))
    op.add_column('scan_jobs', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('scan_jobs', sa.Column('mime_type', sa.String(length=100), nullable=True))
    op.add_column('scan_jobs', sa.Column('progress', sa.Integer(), nullable=False))
    op.add_column('scan_jobs', sa.Column('current_stage', sa.String(), nullable=True))
    op.add_column('scan_jobs', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('scan_jobs', sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('scan_jobs', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('scan_jobs', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('scan_jobs', 'original_filename',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('scan_jobs', 'file_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('scan_jobs', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::text"))
    op.alter_column('scan_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scan_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('scan_jobs_profile_id_fkey'), 'scan_jobs', type_='foreignkey')
    op.drop_constraint(op.f('scan_jobs_user_id_fkey'), 'scan_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'scan_jobs', 'users', ['user_id'], ['id'])
    op.drop_column('scan_jobs', 'profile_id')
    op.add_column('users', sa.Column('active_profile_id', sa.UUID(), nullable=True))
    op.alter_column('users', 'firebase_uid',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'is_email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_firebase_uid_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_active_profile_id'), 'users', ['active_profile_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_foreign_key('fk_user_active_profile', 'users', 'profiles', ['active_profile_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_active_profile', 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_active_profile_id'), table_name='users')
    op.create_unique_constraint(op.f('users_firebase_uid_key'), 'users', ['firebase_uid'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'avatar_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'firebase_uid',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('users', 'active_profile_id')
    op.add_column('scan_jobs', sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'scan_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('scan_jobs_user_id_fkey'), 'scan_jobs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('scan_jobs_profile_id_fkey'), 'scan_jobs', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.alter_column('scan_jobs', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scan_jobs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scan_jobs', 'status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::text"))
    op.alter_column('scan_jobs', 'file_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('scan_jobs', 'original_filename',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('scan_jobs', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('scan_jobs', 'completed_at')
    op.drop_column('scan_jobs', 'uploaded_at')
    op.drop_column('scan_jobs', 'error_message')
    op.drop_column('scan_jobs', 'current_stage')
    op.drop_column('scan_jobs', 'progress')
    op.drop_column('scan_jobs', 'mime_type')
    op.drop_column('scan_jobs', 'file_size')
    op.drop_column('scan_jobs', 'stored_filename')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key(op.f('reports_profile_id_fkey'), 'reports', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('reports_scan_job_id_fkey'), 'reports', 'scan_jobs', ['scan_job_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_reports_firebase_uid'), table_name='reports')
    op.alter_column('reports', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reports', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reports', 'hospital_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('reports', 'mime_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('reports', 'stored_filename',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('reports', 'original_filename',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('reports', 'report_type',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'LAB_REPORT'::text"))
    op.alter_column('reports', 'scan_job_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('reports', 'profile_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('reports', 'firebase_uid')
    op.drop_index(op.f('ix_reference_biomarkers_name'), table_name='reference_biomarkers')
    op.drop_index(op.f('ix_reference_biomarkers_aliases'), table_name='reference_biomarkers')
    op.alter_column('reference_biomarkers', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reference_biomarkers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reference_biomarkers', 'age_group',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('reference_biomarkers', 'gender',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('reference_biomarkers', 'unit',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('reference_biomarkers', 'category',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('reference_biomarkers', 'aliases',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('reference_biomarkers', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('reference_biomarkers', 'severity_weight')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key(op.f('profiles_user_id_fkey'), 'profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_profiles_firebase_uid'), table_name='profiles')
    op.alter_column('profiles', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('profiles', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('profiles', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('profiles', 'relationship_type',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'Self'::text"))
    op.alter_column('profiles', 'blood_group',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('profiles', 'gender',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('profiles', 'full_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('profiles', 'firebase_uid')
    op.add_column('biomarkers', sa.Column('is_abnormal', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'biomarkers', type_='foreignkey')
    op.create_foreign_key(op.f('biomarkers_report_id_fkey'), 'biomarkers', 'reports', ['report_id'], ['id'], ondelete='CASCADE')
    op.alter_column('biomarkers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('biomarkers', 'category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('biomarkers', 'unit',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('biomarkers', 'value',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('biomarkers', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('biomarkers', 'report_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('biomarkers', 'updated_at')
    op.drop_column('biomarkers', 'confidence_score')
    op.drop_column('biomarkers', 'clinical_significance')
    op.drop_column('biomarkers', 'reference_range')
    op.drop_column('biomarkers', 'severity')
    op.drop_index(op.f('ix_ai_insights_severity'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_risk_level'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_report_id'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_insight_type'), table_name='ai_insights')
    op.alter_column('ai_insights', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_insights', 'severity',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ai_insights', 'title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ai_insights', 'insight_type',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ai_insights', 'report_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('ai_insights', 'updated_at')
    op.drop_column('ai_insights', 'provider')
    op.drop_column('ai_insights', 'confidence_score')
    op.drop_column('ai_insights', 'recommendations')
    op.drop_column('ai_insights', 'risk_level')
    op.drop_column('ai_insights', 'summary')
    # ### end Alembic commands ###
