"""update scan job upload fields

Revision ID: 851423542287
Revises: 66ade1cdd2e0
Create Date: 2026-05-09 21:42:34.816498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '851423542287'
down_revision: Union[str, Sequence[str], None] = '66ade1cdd2e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_jobs', sa.Column('original_filename', sa.String(), nullable=False))
    op.add_column('scan_jobs', sa.Column('stored_filename', sa.String(), nullable=False))
    op.add_column('scan_jobs', sa.Column('file_path', sa.String(), nullable=False))
    op.add_column('scan_jobs', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('scan_jobs', sa.Column('mime_type', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'scan_jobs', ['stored_filename'])
    op.drop_column('scan_jobs', 'file_name')
    op.drop_column('scan_jobs', 'file_url')
    op.drop_column('scan_jobs', 'file_type')
    op.drop_column('scan_jobs', 'file_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_jobs', sa.Column('file_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('scan_jobs', sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('scan_jobs', sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('scan_jobs', sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'scan_jobs', type_='unique')
    op.drop_column('scan_jobs', 'mime_type')
    op.drop_column('scan_jobs', 'file_size')
    op.drop_column('scan_jobs', 'file_path')
    op.drop_column('scan_jobs', 'stored_filename')
    op.drop_column('scan_jobs', 'original_filename')
    # ### end Alembic commands ###
