"""add reference biomarkers table

Revision ID: af5cc2a82164
Revises: 03fa51742f1d
Create Date: 2026-05-10 10:12:39.053656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af5cc2a82164'
down_revision: Union[str, Sequence[str], None] = '03fa51742f1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_biomarkers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('aliases', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('age_group', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_biomarkers_category'), 'reference_biomarkers', ['category'], unique=False)
    op.create_index(op.f('ix_reference_biomarkers_name'), 'reference_biomarkers', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reference_biomarkers_name'), table_name='reference_biomarkers')
    op.drop_index(op.f('ix_reference_biomarkers_category'), table_name='reference_biomarkers')
    op.drop_table('reference_biomarkers')
    # ### end Alembic commands ###
